const plantData = {
    Lavender: {
      description: 'Lavender is a flowering plant in the mint family.',
      family: 'Lamiaceae',
      type: 'Perennial',
      seasonOfInterest: 'Summer',
      height: '12 to 48 inches (30 to 120 cm)',
    },
    Coleus: {
      description: 'Coleus is a tropical perennial plant.',
      family: 'Lamiaceae',
      type: 'Perennial',
      seasonOfInterest: 'Spring to Fall',
      height: '12 to 36 inches (30 to 90 cm)',
    },
    'Lagerstroemia Lipan': {
      description: 'Lagerstroemia Lipan is a variety of the crape myrtle tree native to Southeast Asia and Australia.',
      family: 'Lythraceae',
      type: 'Shrub or small tree',
      seasonOfInterest: 'Summer to Fall',
      height: '8 to 12 feet (2.4 to 3.6 meters)',
    },
    'Centaurea': {
      description: 'Centaurea is a genus of flowering plants in the family Asteraceae.',
      family: 'Asteraceae',
      type: 'Annual or perennial',
      seasonOfInterest: 'Summer',
      height: '12 to 40 inches (30 to 100 cm)',
    },
    'Lucky Nut': {
      description: 'Thevetia peruviana, commonly known as Lucky Nut, is a small tree native to Central and South America.',
      family: 'Apocynaceae',
      type: 'Evergreen tree',
      seasonOfInterest: 'Spring to Fall',
      height: '6 to 15 feet (1.8 to 4.5 meters)',
    },
    'Aloe Cameronii': {
    description: 'Aloe cameronii is a slow-growing succulent native to Zimbabwe and Malawi.',
    family: 'Asphodelaceae',
    type: 'Perennial',
    seasonOfInterest: 'Winter to Spring',
    height: '12 to 24 inches (30 to 60 cm)',
    },
    'Aloe Maculata': {
    description: 'Aloe maculata is a species of flowering succulent plant native to southern Africa.',
    family: 'Asphodelaceae',
    type: 'Perennial',
    seasonOfInterest: 'Spring to Summer',
    height: '12 to 18 inches (30 to 45 cm)',
    },
    'Camellia': {
    description: 'Camellia is a genus of flowering plants native to East Asia.',
    family: 'Theaceae',
    type: 'Evergreen shrub or small tree',
    seasonOfInterest: 'Winter to Spring',
    height: '3 to 20 feet (1 to 6 meters)',
    },
    'Dracaena Draco': {
    description: 'Dracaena draco, also known as the dragon tree, is a subtropical tree native to the Canary Islands, Madeira, and Cape Verde.',
    family: 'Asparagaceae',
    type: 'Evergreen tree',
    seasonOfInterest: 'Year-round',
    height: '20 to 30 feet (6 to 9 meters)',
    },
    'Hibiscus': {
    description: 'Hibiscus is a genus of flowering plants in the mallow family.',
    family: 'Malvaceae',
    type: 'Annual or perennial',
    seasonOfInterest: 'Summer to Fall',
    height: '3 to 15 feet (1 to 4.5 meters)',
    },
    'Salvia': {
    description: 'Salvia is a genus of herbaceous plants and shrubs in the mint family.',
    family: 'Lamiaceae',
    type: 'Annual or perennial',
    seasonOfInterest: 'Summer to Fall',
    height: '18 to 60 inches (45 to 150 cm)',
    },
    'Sandburs': {
    description: 'Sandburs are annual grasses belonging to the genus Cenchrus, known for their sharp, spiny seed heads.',
    family: 'Poaceae',
    type: 'Annual grass',
    seasonOfInterest: 'Spring to Fall',
    height: '6 to 36 inches (15 to 90 cm)',
    },
    'Fountain Grass': {
    description: 'Fountain grass is an ornamental grass native to Asia and Australia, often used in landscaping for its attractive, arching form.',
    family: 'Poaceae',
    type: 'Perennial grass',
    seasonOfInterest: 'Summer to Fall',
    height: '18 to 60 inches (45 to 150 cm)',
    },
  };
  
  export default plantData;
  